name: reusable-semantic-pr
on:
  workflow_call:
    inputs:
      types:
        required: false
        type: string
        default: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert
      require_scope:
        required: false
        type: boolean
        default: false
permissions:
  pull-requests: write
jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: ${{ inputs.types }}
          requireScope: ${{ inputs.require_scope }}